// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: graytorrent.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Torrent_State int32

const (
	Torrent_DOWNLOADING Torrent_State = 0
	Torrent_STOPPED     Torrent_State = 1
	Torrent_STALLED     Torrent_State = 2
	Torrent_SEEDING     Torrent_State = 3
	Torrent_COMPLETE    Torrent_State = 4
)

// Enum value maps for Torrent_State.
var (
	Torrent_State_name = map[int32]string{
		0: "DOWNLOADING",
		1: "STOPPED",
		2: "STALLED",
		3: "SEEDING",
		4: "COMPLETE",
	}
	Torrent_State_value = map[string]int32{
		"DOWNLOADING": 0,
		"STOPPED":     1,
		"STALLED":     2,
		"SEEDING":     3,
		"COMPLETE":    4,
	}
)

func (x Torrent_State) Enum() *Torrent_State {
	p := new(Torrent_State)
	*p = x
	return p
}

func (x Torrent_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Torrent_State) Descriptor() protoreflect.EnumDescriptor {
	return file_graytorrent_proto_enumTypes[0].Descriptor()
}

func (Torrent_State) Type() protoreflect.EnumType {
	return &file_graytorrent_proto_enumTypes[0]
}

func (x Torrent_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Torrent_State.Descriptor instead.
func (Torrent_State) EnumDescriptor() ([]byte, []int) {
	return file_graytorrent_proto_rawDescGZIP(), []int{1, 0}
}

type SessionRequest_Type int32

const (
	SessionRequest_ADD    SessionRequest_Type = 0
	SessionRequest_REMOVE SessionRequest_Type = 1
	SessionRequest_START  SessionRequest_Type = 2
	SessionRequest_STOP   SessionRequest_Type = 3
)

// Enum value maps for SessionRequest_Type.
var (
	SessionRequest_Type_name = map[int32]string{
		0: "ADD",
		1: "REMOVE",
		2: "START",
		3: "STOP",
	}
	SessionRequest_Type_value = map[string]int32{
		"ADD":    0,
		"REMOVE": 1,
		"START":  2,
		"STOP":   3,
	}
)

func (x SessionRequest_Type) Enum() *SessionRequest_Type {
	p := new(SessionRequest_Type)
	*p = x
	return p
}

func (x SessionRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_graytorrent_proto_enumTypes[1].Descriptor()
}

func (SessionRequest_Type) Type() protoreflect.EnumType {
	return &file_graytorrent_proto_enumTypes[1]
}

func (x SessionRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionRequest_Type.Descriptor instead.
func (SessionRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_graytorrent_proto_rawDescGZIP(), []int{6, 0}
}

type SessionReply_Event int32

const (
	SessionReply_UPDATE  SessionReply_Event = 0 // Show changes to progress, upload/download rates, and state
	SessionReply_ADDED   SessionReply_Event = 1
	SessionReply_REMOVED SessionReply_Event = 2
	SessionReply_STARTED SessionReply_Event = 3
	SessionReply_STOPPED SessionReply_Event = 4
)

// Enum value maps for SessionReply_Event.
var (
	SessionReply_Event_name = map[int32]string{
		0: "UPDATE",
		1: "ADDED",
		2: "REMOVED",
		3: "STARTED",
		4: "STOPPED",
	}
	SessionReply_Event_value = map[string]int32{
		"UPDATE":  0,
		"ADDED":   1,
		"REMOVED": 2,
		"STARTED": 3,
		"STOPPED": 4,
	}
)

func (x SessionReply_Event) Enum() *SessionReply_Event {
	p := new(SessionReply_Event)
	*p = x
	return p
}

func (x SessionReply_Event) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionReply_Event) Descriptor() protoreflect.EnumDescriptor {
	return file_graytorrent_proto_enumTypes[2].Descriptor()
}

func (SessionReply_Event) Type() protoreflect.EnumType {
	return &file_graytorrent_proto_enumTypes[2]
}

func (x SessionReply_Event) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionReply_Event.Descriptor instead.
func (SessionReply_Event) EnumDescriptor() ([]byte, []int) {
	return file_graytorrent_proto_rawDescGZIP(), []int{7, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graytorrent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_graytorrent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_graytorrent_proto_rawDescGZIP(), []int{0}
}

type Torrent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InfoHash    []byte        `protobuf:"bytes,2,opt,name=infoHash,proto3" json:"infoHash,omitempty"`
	TotalLength uint32        `protobuf:"varint,3,opt,name=totalLength,proto3" json:"totalLength,omitempty"`
	Left        uint32        `protobuf:"varint,4,opt,name=left,proto3" json:"left,omitempty"`
	DownRate    uint32        `protobuf:"varint,5,opt,name=downRate,proto3" json:"downRate,omitempty"`
	UpRate      uint32        `protobuf:"varint,6,opt,name=upRate,proto3" json:"upRate,omitempty"`
	State       Torrent_State `protobuf:"varint,7,opt,name=state,proto3,enum=graytorrent.Torrent_State" json:"state,omitempty"`
	Id          uint32        `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Torrent) Reset() {
	*x = Torrent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graytorrent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Torrent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Torrent) ProtoMessage() {}

func (x *Torrent) ProtoReflect() protoreflect.Message {
	mi := &file_graytorrent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Torrent.ProtoReflect.Descriptor instead.
func (*Torrent) Descriptor() ([]byte, []int) {
	return file_graytorrent_proto_rawDescGZIP(), []int{1}
}

func (x *Torrent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Torrent) GetInfoHash() []byte {
	if x != nil {
		return x.InfoHash
	}
	return nil
}

func (x *Torrent) GetTotalLength() uint32 {
	if x != nil {
		return x.TotalLength
	}
	return 0
}

func (x *Torrent) GetLeft() uint32 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *Torrent) GetDownRate() uint32 {
	if x != nil {
		return x.DownRate
	}
	return 0
}

func (x *Torrent) GetUpRate() uint32 {
	if x != nil {
		return x.UpRate
	}
	return 0
}

func (x *Torrent) GetState() Torrent_State {
	if x != nil {
		return x.State
	}
	return Torrent_DOWNLOADING
}

func (x *Torrent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Torrents []*Torrent `protobuf:"bytes,1,rep,name=torrents,proto3" json:"torrents,omitempty"`
}

func (x *ListReply) Reset() {
	*x = ListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graytorrent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReply) ProtoMessage() {}

func (x *ListReply) ProtoReflect() protoreflect.Message {
	mi := &file_graytorrent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReply.ProtoReflect.Descriptor instead.
func (*ListReply) Descriptor() ([]byte, []int) {
	return file_graytorrent_proto_rawDescGZIP(), []int{2}
}

func (x *ListReply) GetTorrents() []*Torrent {
	if x != nil {
		return x.Torrents
	}
	return nil
}

type TorrentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InfoHash []byte `protobuf:"bytes,1,opt,name=infoHash,proto3" json:"infoHash,omitempty"`
	Id       uint32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"` // May remove in the future, only here to make cli input easier
}

func (x *TorrentRequest) Reset() {
	*x = TorrentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graytorrent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentRequest) ProtoMessage() {}

func (x *TorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graytorrent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentRequest.ProtoReflect.Descriptor instead.
func (*TorrentRequest) Descriptor() ([]byte, []int) {
	return file_graytorrent_proto_rawDescGZIP(), []int{3}
}

func (x *TorrentRequest) GetInfoHash() []byte {
	if x != nil {
		return x.InfoHash
	}
	return nil
}

func (x *TorrentRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Magnet    bool   `protobuf:"varint,2,opt,name=magnet,proto3" json:"magnet,omitempty"`
	Directory string `protobuf:"bytes,3,opt,name=directory,proto3" json:"directory,omitempty"`
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graytorrent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graytorrent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_graytorrent_proto_rawDescGZIP(), []int{4}
}

func (x *AddRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddRequest) GetMagnet() bool {
	if x != nil {
		return x.Magnet
	}
	return false
}

func (x *AddRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

type RemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TorrentRequest *TorrentRequest `protobuf:"bytes,1,opt,name=torrentRequest,proto3" json:"torrentRequest,omitempty"`
	RmFiles        bool            `protobuf:"varint,2,opt,name=rmFiles,proto3" json:"rmFiles,omitempty"`
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graytorrent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graytorrent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_graytorrent_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveRequest) GetTorrentRequest() *TorrentRequest {
	if x != nil {
		return x.TorrentRequest
	}
	return nil
}

func (x *RemoveRequest) GetRmFiles() bool {
	if x != nil {
		return x.RmFiles
	}
	return false
}

type SessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type SessionRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=graytorrent.SessionRequest_Type" json:"type,omitempty"`
	// Union (Oneof)
	//
	// Types that are assignable to Request:
	//	*SessionRequest_Add
	//	*SessionRequest_Remove
	//	*SessionRequest_Start
	//	*SessionRequest_Stop
	Request isSessionRequest_Request `protobuf_oneof:"request"`
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graytorrent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graytorrent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_graytorrent_proto_rawDescGZIP(), []int{6}
}

func (x *SessionRequest) GetType() SessionRequest_Type {
	if x != nil {
		return x.Type
	}
	return SessionRequest_ADD
}

func (m *SessionRequest) GetRequest() isSessionRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *SessionRequest) GetAdd() *AddRequest {
	if x, ok := x.GetRequest().(*SessionRequest_Add); ok {
		return x.Add
	}
	return nil
}

func (x *SessionRequest) GetRemove() *RemoveRequest {
	if x, ok := x.GetRequest().(*SessionRequest_Remove); ok {
		return x.Remove
	}
	return nil
}

func (x *SessionRequest) GetStart() *TorrentRequest {
	if x, ok := x.GetRequest().(*SessionRequest_Start); ok {
		return x.Start
	}
	return nil
}

func (x *SessionRequest) GetStop() *TorrentRequest {
	if x, ok := x.GetRequest().(*SessionRequest_Stop); ok {
		return x.Stop
	}
	return nil
}

type isSessionRequest_Request interface {
	isSessionRequest_Request()
}

type SessionRequest_Add struct {
	Add *AddRequest `protobuf:"bytes,2,opt,name=add,proto3,oneof"`
}

type SessionRequest_Remove struct {
	Remove *RemoveRequest `protobuf:"bytes,3,opt,name=remove,proto3,oneof"`
}

type SessionRequest_Start struct {
	Start *TorrentRequest `protobuf:"bytes,4,opt,name=start,proto3,oneof"`
}

type SessionRequest_Stop struct {
	Stop *TorrentRequest `protobuf:"bytes,5,opt,name=stop,proto3,oneof"`
}

func (*SessionRequest_Add) isSessionRequest_Request() {}

func (*SessionRequest_Remove) isSessionRequest_Request() {}

func (*SessionRequest_Start) isSessionRequest_Request() {}

func (*SessionRequest_Stop) isSessionRequest_Request() {}

type SessionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Torrent *Torrent           `protobuf:"bytes,1,opt,name=torrent,proto3" json:"torrent,omitempty"`
	Event   SessionReply_Event `protobuf:"varint,2,opt,name=event,proto3,enum=graytorrent.SessionReply_Event" json:"event,omitempty"`
}

func (x *SessionReply) Reset() {
	*x = SessionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graytorrent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReply) ProtoMessage() {}

func (x *SessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_graytorrent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReply.ProtoReflect.Descriptor instead.
func (*SessionReply) Descriptor() ([]byte, []int) {
	return file_graytorrent_proto_rawDescGZIP(), []int{7}
}

func (x *SessionReply) GetTorrent() *Torrent {
	if x != nil {
		return x.Torrent
	}
	return nil
}

func (x *SessionReply) GetEvent() SessionReply_Event {
	if x != nil {
		return x.Event
	}
	return SessionReply_UPDATE
}

var File_graytorrent_proto protoreflect.FileDescriptor

var file_graytorrent_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0xb4, 0x02, 0x0a, 0x07, 0x54, 0x6f,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x66,
	0x6f, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x69, 0x6e, 0x66,
	0x6f, 0x48, 0x61, 0x73, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x6f, 0x77, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64,
	0x6f, 0x77, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x52, 0x61, 0x74,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x70, 0x52, 0x61, 0x74, 0x65, 0x12,
	0x30, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a,
	0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x6f, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x4d, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x4f,
	0x57, 0x4e, 0x4c, 0x4f, 0x41, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x4c,
	0x4c, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45, 0x45, 0x44, 0x49, 0x4e, 0x47,
	0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x04,
	0x22, 0x3d, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x30, 0x0a,
	0x08, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x6f,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0x3c, 0x0a, 0x0e, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x66, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x69, 0x6e, 0x66, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x56, 0x0a,
	0x0a, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x6e, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x0e, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x6f, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0e, 0x74, 0x6f, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x6d, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x6d,
	0x46, 0x69, 0x6c, 0x65, 0x73, 0x22, 0xce, 0x02, 0x0a, 0x0e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2b,
	0x0a, 0x03, 0x61, 0x64, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x72,
	0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x03, 0x61, 0x64, 0x64, 0x12, 0x34, 0x0a, 0x06, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x72,
	0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x12, 0x33, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x54,
	0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x31, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x2e, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x22, 0x30, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45,
	0x4d, 0x4f, 0x56, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10,
	0x02, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x03, 0x42, 0x09, 0x0a, 0x07, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xbc, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2e, 0x0a, 0x07, 0x74, 0x6f, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x72, 0x61, 0x79, 0x74,
	0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x07,
	0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x35, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x45,
	0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54,
	0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x44, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x50,
	0x50, 0x45, 0x44, 0x10, 0x04, 0x32, 0xf8, 0x02, 0x0a, 0x0e, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x12, 0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x34,
	0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x1a,
	0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x67, 0x72, 0x61,
	0x79, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x3a, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x61, 0x79,
	0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x04,
	0x53, 0x74, 0x6f, 0x70, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x2e, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b,
	0x79, 0x6c, 0x65, 0x63, 0x37, 0x32, 0x35, 0x2f, 0x67, 0x72, 0x61, 0x79, 0x74, 0x6f, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_graytorrent_proto_rawDescOnce sync.Once
	file_graytorrent_proto_rawDescData = file_graytorrent_proto_rawDesc
)

func file_graytorrent_proto_rawDescGZIP() []byte {
	file_graytorrent_proto_rawDescOnce.Do(func() {
		file_graytorrent_proto_rawDescData = protoimpl.X.CompressGZIP(file_graytorrent_proto_rawDescData)
	})
	return file_graytorrent_proto_rawDescData
}

var file_graytorrent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_graytorrent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_graytorrent_proto_goTypes = []interface{}{
	(Torrent_State)(0),       // 0: graytorrent.Torrent.State
	(SessionRequest_Type)(0), // 1: graytorrent.SessionRequest.Type
	(SessionReply_Event)(0),  // 2: graytorrent.SessionReply.Event
	(*Empty)(nil),            // 3: graytorrent.Empty
	(*Torrent)(nil),          // 4: graytorrent.Torrent
	(*ListReply)(nil),        // 5: graytorrent.ListReply
	(*TorrentRequest)(nil),   // 6: graytorrent.TorrentRequest
	(*AddRequest)(nil),       // 7: graytorrent.AddRequest
	(*RemoveRequest)(nil),    // 8: graytorrent.RemoveRequest
	(*SessionRequest)(nil),   // 9: graytorrent.SessionRequest
	(*SessionReply)(nil),     // 10: graytorrent.SessionReply
}
var file_graytorrent_proto_depIdxs = []int32{
	0,  // 0: graytorrent.Torrent.state:type_name -> graytorrent.Torrent.State
	4,  // 1: graytorrent.ListReply.torrents:type_name -> graytorrent.Torrent
	6,  // 2: graytorrent.RemoveRequest.torrentRequest:type_name -> graytorrent.TorrentRequest
	1,  // 3: graytorrent.SessionRequest.type:type_name -> graytorrent.SessionRequest.Type
	7,  // 4: graytorrent.SessionRequest.add:type_name -> graytorrent.AddRequest
	8,  // 5: graytorrent.SessionRequest.remove:type_name -> graytorrent.RemoveRequest
	6,  // 6: graytorrent.SessionRequest.start:type_name -> graytorrent.TorrentRequest
	6,  // 7: graytorrent.SessionRequest.stop:type_name -> graytorrent.TorrentRequest
	4,  // 8: graytorrent.SessionReply.torrent:type_name -> graytorrent.Torrent
	2,  // 9: graytorrent.SessionReply.event:type_name -> graytorrent.SessionReply.Event
	3,  // 10: graytorrent.TorrentService.List:input_type -> graytorrent.Empty
	7,  // 11: graytorrent.TorrentService.Add:input_type -> graytorrent.AddRequest
	8,  // 12: graytorrent.TorrentService.Remove:input_type -> graytorrent.RemoveRequest
	6,  // 13: graytorrent.TorrentService.Start:input_type -> graytorrent.TorrentRequest
	6,  // 14: graytorrent.TorrentService.Stop:input_type -> graytorrent.TorrentRequest
	9,  // 15: graytorrent.TorrentService.Session:input_type -> graytorrent.SessionRequest
	5,  // 16: graytorrent.TorrentService.List:output_type -> graytorrent.ListReply
	3,  // 17: graytorrent.TorrentService.Add:output_type -> graytorrent.Empty
	3,  // 18: graytorrent.TorrentService.Remove:output_type -> graytorrent.Empty
	3,  // 19: graytorrent.TorrentService.Start:output_type -> graytorrent.Empty
	3,  // 20: graytorrent.TorrentService.Stop:output_type -> graytorrent.Empty
	10, // 21: graytorrent.TorrentService.Session:output_type -> graytorrent.SessionReply
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_graytorrent_proto_init() }
func file_graytorrent_proto_init() {
	if File_graytorrent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_graytorrent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graytorrent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Torrent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graytorrent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graytorrent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TorrentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graytorrent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graytorrent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graytorrent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graytorrent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_graytorrent_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*SessionRequest_Add)(nil),
		(*SessionRequest_Remove)(nil),
		(*SessionRequest_Start)(nil),
		(*SessionRequest_Stop)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_graytorrent_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graytorrent_proto_goTypes,
		DependencyIndexes: file_graytorrent_proto_depIdxs,
		EnumInfos:         file_graytorrent_proto_enumTypes,
		MessageInfos:      file_graytorrent_proto_msgTypes,
	}.Build()
	File_graytorrent_proto = out.File
	file_graytorrent_proto_rawDesc = nil
	file_graytorrent_proto_goTypes = nil
	file_graytorrent_proto_depIdxs = nil
}
